### ISSUE TITLE
Improve docs about usage with bundlers

### ISSUE THREAD

**Issue by fabiospampinato** [sindresorhus/import-lazy#15]
I was trying to lazy-load some expensive modules in my webpack-bundled application and I found this  module.

The recommended way of using it is too dynamic for bundlers, as they can't infer what modules are actually getting loaded:

```js
const importLazy = require('import-lazy')(require);
const _ = importLazy('lodash');
```

But it turns out that this module is general enough to support my use case too:

```js
const importLazy = require('import-lazy');
const _ = importLazy(() => require ( 'lodash' ))();
```

But the syntax gets a bit weird.

Perhaps this way of using it could be mentioned explicitly in the readme.

**Comment by sindresorhus** [comment]
Sure, PR welcome :)
