### ISSUE TITLE
Drop Node 5 support in v3.0.0

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/import-lazy#8]
![schedule as of may 2017](https://cloud.githubusercontent.com/assets/1402241/26492343/1996f818-4246-11e7-9ee6-4cf4662446a0.png)

Node 6 is the current LTS release, Node 5 is not maintained, Node 4 is in maintenance mode.

It'd make sense to push the Proxy version as the default version or as the only version. Who needs Node 4 support can install the current version (v2.x)

**Comment by sindresorhus** [comment]
> It'd make sense to push the Proxy version as the default version or as the only version. Who needs Node 4 support can install the current version (v2.x)

Sure, if you're or anyone else is willing to do the code, test, and readme updates.

**Comment by bfred-it** [comment]
Pretty busy on refined-github at the moment :P
